### ISSUE TITLE
QCommandLineParser: No such file or directory

### ISSUE THREAD

**Issue by Aidoboy** [bparker06/msi-keyboard#3]
I don't really know what do to about this. Any help?

```
g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I. -o main.o main.cpp
main.cpp:11:30: fatal error: QCommandLineParser: No such file or directory
compilation terminated.
Makefile:210: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

**Comment by bparker06** [comment]
Hi @Aidoboy,

It looks like you are trying to compile it against Qt 4 instead of Qt 5.
Your particular distribution might have a different name for the qmake
version for Qt 5, such as "qmake-qt5". I would try that and make sure the
Qt 5 packages are installed as well. If you cannot get it to work, let me
know what distro you're using and I'll try to help as best I can.

Thanks!

**Comment by Aidoboy** [comment]
Which QT5 packages do I need?

**Comment by bparker06** [comment]
You should only need the "base" or "core" package, some distros also
package qmake separately so you might need a qmake-qt5 package also, but
without knowing what distro you have it's hard to know exactly what you
need.

**Comment by Aidoboy** [comment]
This is all I can see with tab complete:
```
$ sudo apt-get install qt5
qt5ct                          qt5keychain-dev
qt5-default                    qt5-qmake
qt5-doc                        qt5-qmake-arm-linux-gnueabihf
qt5-doc-html                   qt5-qmake-cross-armhf
qt5gstreamer-dbg               qt5-qmake-gles
qt5-image-formats-plugins      qt5-style-plugins
```

And I'm running Ubuntu 15.10

**Comment by giuliopaci** [comment]
Then you need these packages:
qt5-qmake
qtbase5-dev
libhidapi-dev

Then you can run:
QT_SELECT=5 qmake -makefile
make

and it should work.

**Comment by Aidoboy** [comment]
Woohoo! It worked!
