### ISSUE TITLE
auto start on boot and suspension resume

### ISSUE THREAD

**Issue by gavsiu** [bparker06/msi-keyboard#5]
I'm relatively new to Linux and I've been trying to figure out how to turn the backlight on automatically on boot and resume. I don't know where else to go for help, so I was hoping someone here could help.

I've tried using 2 services for boot and resume and the script runs fine on startup, but I've been having trouble getting the backlight to reliably turn on after coming out of standby. By reliably, I mean I've only seen it turn on once.

Most of the times, it says:

    May 13 10:52:25 Laptop systemd[1]: Started keyboard backlight on resume.
    May 13 10:52:29 Laptop msi-keyboard.sh[7273]: cannot open usb device

This is my systemd service for resume and the startup script is almost identical:

    [Unit]

    Description=keyboard backlight on resume
    After=suspend.target

    [Service]
    Type=simple
    ExecStart=~/bin/msi-keyboard.sh

    [Install]
    WantedBy=suspend.target

Running the same script manually after resuming turns on the light: 

    #!/bin/bash
    COLOR="orange"
    INTENSITY="light"

    if [[ $1 == "off" ]]; then
      COLOR="off"
    fi

    msi-keyboard -m normal -c left,$COLOR,$INTENSITY -c middle,$COLOR,$INTENSITY -c right,$COLOR,$INTENSITY

**Comment by bparker06** [comment]
Hi @gavsiu, it looks like your script happens to run too soon after resuming, before the USB device is ready. That would explain the intermittent issues. Here is one possible solution involving modifying the udev rule to run a script with the RUN+= keyword after the keyboard device is detected:

http://stackoverflow.com/questions/18463755/linux-start-daemon-on-connected-usb-serial-dongle

Hope this helps.

**Comment by gavsiu** [comment]
Sorry, I forgot I posted here. I found a solution that seems to be working. I changed the service type from `simple` to `idle`. The light turns on after resume 100% of the time so far, although the service still says it `cannot open usb`.

    [Unit]

    Description=keyboard backlight on resume
    After=suspend.target

    [Service]
    Type=simple
    ExecStart=~/bin/msi-keyboard.sh

    [Install]
    WantedBy=suspend.target
