### ISSUE TITLE
Cannot open USB Device

### ISSUE THREAD

**Issue by JackofSpades707** [bparker06/msi-keyboard#7]
first off, thank you for making this *nix alternative :)

Second, I'm getting an error and not quite sure how to proceed here, I know that's not very helpful so here's what I see :
http://i.imgur.com/uZNjTKt.png

is there anything driver related I need to fiddle with here? Here's my xorg.conf if that matters:
http://pastebin.com/8KM6L6v7

OS : Arch Linux
Kernel: x86_64 Linux 4.7.6-1-ARCH
DE : Gnome
WM : GNOME Shell

**Comment by bparker06** [comment]
Hi @JackofSpades707, in the README we have this line:

Make sure to copy 99-msi.rules to /etc/udev/rules.d unless you want to run the program as root. Requires a reboot or maybe just a reload of udev rules to work correctly.

Have you checked into this?

**Comment by JackofSpades707** [comment]
http://i.imgur.com/r8VVY20.png

Yes and I have rebooted as well.

Something I should mention is that the lights worked just fine for a day or two, and then they seemed to randomly just dim until they died, now I have tried this tool from the AUR : https://aur.archlinux.org/packages/msi-keyboard-git/
As well as : 
https://aur.archlinux.org/packages/msiklm-git/

But alas nothing seems to be working to bring the colors back to my steel series apex m800 :/

**Comment by bparker06** [comment]
It's possible your particular keyboard might have a different VID/PID from the one in the udev rules file... does it work if you run the program as root?

**Comment by JackofSpades707** [comment]
Just tried running it as root with no luck.
http://i.imgur.com/eJhSBFK.png

Clarification : I didn't install either of those packages until after the lights on the keyboard appeared to die (about 1-2 days after switching from windows10 to arch)

**Comment by bparker06** [comment]
Perhaps the circuitry controlling the lights has failed. Are you able to change it still under Windows?

**Comment by JackofSpades707** [comment]
I don't have my existing windows partition anymore, I tried to set it up with a VM but the VM saw the keyboard as a standard keyboard so the steel series engine wasn't aware it was a steel series keyboard.

I will setup windows on a separate hdd and post back.

**Comment by JackofSpades707** [comment]
Turns out that I had it disabled at a hardware level somehow, I'm unsure how I did that originally but all is good now. :)

**Comment by Aashit-Sharma** [comment]
@JackofSpades707 how did you enable it at hardware level ? I am using arch too and am facing the exact same issue.
