### ISSUE TITLE
Support for GE63VR

### ISSUE THREAD

**Issue by redkite** [bparker06/msi-keyboard#9]
I have an MSI GE63VR 7RF and am trying to get msi-keyboard running on it. It seems to have another keyboard, or at least different a vendor id:
`hid-generic 0003:1038:1122.0003: hiddev0,hidraw2: USB HID v1.11 Device [SteelSeries SteelSeries KLC] on usb-0000:00:14.0-9/input0`
and
`Bus 001 Device 003: ID 1038:1122 SteelSeries ApS`
I am not totally sure it's the correct device, but there is not a lot of different USB devices and none of the ids matches.

I adjusted the udev-rule and also the id in keyboard.cpp. The code compiles and I can use it without any problems, but the commands simply will not show any change on the keyboard itself.

Is there any good way to debug this and try to get it working on the GE63?

**Comment by bwrsandman** [comment]
The MSI GS65 also has different ids:

```
# lsusb -vs 001:002

Bus 001 Device 002: ID 1038:1122 SteelSeries ApS 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1038 SteelSeries ApS
  idProduct          0x1122 
  bcdDevice            2.29
  iManufacturer           1 SteelSeries
  iProduct                2 SteelSeries KLC
  iSerial                 0 
  bNumConfigurations      1
```

**Comment by redkite** [comment]
@Askannz Wow, thank you. Finally a (even very well) working tool to control the RGB keys. Well appreciated, closing since it is "solved" for me. If there is more need for someone else, feel free to reopen.
